/**
 * AIXORD Companion - Background Service Worker
 *
 * Handles Chrome extension lifecycle and side panel management.
 */

import type { CompanionState } from '../types';
import { createDefaultState } from '../types';

// Storage key for state
const STORAGE_KEY = 'aixord_companion_state';

/**
 * Initialize the extension on install
 */
chrome.runtime.onInstalled.addListener(async () => {
  console.log('[AIXORD Companion] Extension installed');

  // Initialize state if not exists
  const result = await chrome.storage.local.get(STORAGE_KEY);
  if (!result[STORAGE_KEY]) {
    const defaultState = createDefaultState();
    await chrome.storage.local.set({ [STORAGE_KEY]: defaultState });
    console.log('[AIXORD Companion] Default state initialized');
  }

  // Enable side panel to open on action click
  await chrome.sidePanel.setPanelBehavior({ openPanelOnActionClick: true });
  console.log('[AIXORD Companion] Side panel behavior configured');
});

/**
 * Handle extension icon click - open side panel
 * Note: With openPanelOnActionClick: true, this may not be needed,
 * but we keep it as a fallback for programmatic opening
 */
chrome.action.onClicked.addListener(async (tab) => {
  if (tab.id) {
    try {
      await chrome.sidePanel.open({ tabId: tab.id });
    } catch (error) {
      console.error('[AIXORD Companion] Failed to open side panel:', error);
    }
  }
});

/**
 * Message handler for communication with side panel
 */
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  handleMessage(message).then(sendResponse);
  return true; // Keep channel open for async response
});

async function handleMessage(message: { type: string; payload?: unknown }): Promise<unknown> {
  switch (message.type) {
    case 'GET_STATE': {
      const result = await chrome.storage.local.get(STORAGE_KEY);
      return { ok: true, data: result[STORAGE_KEY] ?? createDefaultState() };
    }

    case 'SAVE_STATE': {
      const state = message.payload as CompanionState;
      await chrome.storage.local.set({ [STORAGE_KEY]: state });
      return { ok: true };
    }

    case 'RESET_STATE': {
      const defaultState = createDefaultState();
      await chrome.storage.local.set({ [STORAGE_KEY]: defaultState });
      return { ok: true, data: defaultState };
    }

    case 'GENERATE_HANDOFF': {
      const state = message.payload as CompanionState;
      const handoff = generateHandoff(state);
      return { ok: true, data: handoff };
    }

    default:
      return { ok: false, error: `Unknown message type: ${message.type}` };
  }
}

/**
 * Generate HANDOFF markdown from current state
 */
function generateHandoff(state: CompanionState): string {
  const now = new Date().toISOString();
  const passedGates = Object.entries(state.session.gates)
    .filter(([_, status]) => status === 'passed')
    .map(([id]) => id);

  return `# AIXORD SESSION HANDOFF

**Generated:** ${now}
**Phase:** ${state.session.phase}

## Project
${state.project ? `
- **Name:** ${state.project.name}
- **Description:** ${state.project.description}
- **Created:** ${state.project.createdAt}
` : 'No project configured'}

## Gates Status
${passedGates.length > 0 ? `Passed: ${passedGates.join(', ')}` : 'No gates passed yet'}

## Session Notes
${state.session.notes || 'No notes recorded'}

## Instructions for Next Session
1. Review the gates status above
2. Continue from the ${state.session.phase} phase
3. Pass remaining gates as needed

---
*Generated by AIXORD Companion v1.0.0*
`;
}
